spring.application.name=Category-Product-Application

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:categoryProjectDb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

#Jap Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop

#server configuration
server.port=4041

